### ISSUE TITLE
Feature Request - Additional Progress Animation Type

### ISSUE THREAD

**Issue by timtwalsh** [WeakAuras/WeakAurasStopMotion#1]
I'm working on a project at the moment where I'd like the frame rate to be dependent on a variable state. (Eg High Rage = Higher Framerate)

Variable Framerate as a new animation mode 
- Framerate with a configurable minimum and maximum state
- Could take a resource such as power, buff stacks, haste, crit. (+inverse)
- Frame rate variable, with a configurable modifier.
Eg. Rage as the activation, Min Frame Rate of 4fps, Max of 12fps, 0% rage = 4fps, 100% rage = 12fps.
Eg. Buff Stacks as the activation, Min Frame Rate of 1fps, Max of 6fps, minmum state of 0, maximum state of 3, When the buff >=3 stacks animation runs at 6fps.

Apologies if this isn't the right place to post. Thanks.

**Comment by InfusOnWoW** [comment]
That's actually not that easy to add.

**Comment by timtwalsh** [comment]
No worries, was just a thought :)
