### ISSUE TITLE
Stop Motion Auras Not Showing Any Configuration Tabs

### ISSUE THREAD

**Issue by Crelam** [WeakAuras/WeakAurasStopMotion#4]
Using the WeakAura version 2.17.12-7-ga3a028b5 and Stop Motion version 0.9.5 I am no longer getting any options for Stop Motion weakauras.  The right hand panel (Where display, trigger, conditions, etc.. tabs usually are) is completely blank.  I also receive the following error message:

1x ...Ons\WeakAurasStopMotion\RegionOptions\stopmotion.lua:287: attempt to call field 'PositionOptions' (a nil value)
[string "@WeakAurasStopMotion\RegionOptions\stopmotion.lua"]:287: in function `create'
[string "@WeakAurasOptions\DisplayOptions.lua"]:94: in function `?'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:820: in function `EnsureOptions'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:794: in function `UpdateOptions'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:833: in function `FillOptions'
[string "@WeakAurasOptions\OptionsFrames\OptionsFrame.lua"]:1108: in function `PickDisplay'
[string "@WeakAurasOptions\WeakAurasOptions-2.17.12-7-ga3a028b5.lua"]:1034: in function `PickDisplay'
[string "@WeakAurasOptions\AceGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua"]:579: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:539>

I was able to fix the errant code.

Changing line 287 in RegionOptions\stopmotion.lua from 
     position = WeakAuras.PositionOptions(id, data, 2),
to 
     position = WeakAuras.commonOptions.PositionOptions(id, data, 2),
corrects the issue.

**Comment by InfusOnWoW** [comment]
That should be fixed now.
